default_job = "stm"

[jobs.stm]
command = ["cargo", "check", "--target", "thumbv7em-none-eabihf", "--features", "stm32"]
need_stdout = false
env.CARGO_TERM_COLOR = "always"

[jobs.pc]
command = ["cargo", "check", "--features", "pc"]
need_stdout = false
env.CARGO_TERM_COLOR = "always"
env.RUSTUP_TOOLCHAIN = "stable"

