[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F722RETx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[unstable]
build-std = ["core", "alloc"]

[alias]
build-pc = ["build", "--features", "pc"]
build-stm = ["build", "--target", "thumbv7em-none-eabihf", "--features", "stm32"]
run-stm = ["run", "--target", "thumbv7em-none-eabihf", "--features", "stm32", "--bin", "kasarisw"]
